blank_issues_enabled: false
contact_links:
  - name: Security vulnerabilities
    url: https://github.com/klemmchr/MvvmBlazor
    about: Please report security vulnerabilities via email to git+mvvmblazor@klemm.one
