blank_issues_enabled: false
contact_links:
  - name: Security vulnerabilities
    url: git+mvvmblazor@klemm.one
    about: Please report security vulnerabilities via email to git+mvvmblazor@klemm.one.
