blank_issues_enabled: false
contact_links:
  - name: Security vulnerabilities
    url: https://github.com/klemmchr
    about: Please report security vulnerabilities via email to git+mvvmblazor@klemm.one. A link to my PGP key can be found in my profile.
