on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths:
      - 'samples/**/*'
      - 'src/**/*'
      - '.github/workflows/**/*'

name: Build samples

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master

      - name: Setup .NET
        uses: actions/setup-dotnet@master
        with:
          dotnet-version: '6.0.x'

      - name: Build
        run: dotnet build --configuration Release samples
