on:
  release:
    types: [ published ]

name: Release

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master

      - name: Setup .NET
        uses: actions/setup-dotnet@master
        with:
          dotnet-version: '6.0.x'

      - name: Build
        run: dotnet build -p:ContinuousIntegrationBuild=true --configuration Release src

      - name: Test
        run: dotnet test --configuration Release src

      - name: Publish
        run: >
          dotnet nuget add source --username $GITHUB_REPOSITORY_OWNER --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/$GITHUB_REPOSITORY_OWNER/index.json";
          export VERSION=$(git describe --long --tags --match 'v*' | sed 's/v//' | sed -E 's/[-].+//g');
          echo $VERSION;
          dotnet pack --configuration Release --include-source -p:SymbolPackageFormat=snupkg -p:ContinuousIntegrationBuild=true -p:Version=$VERSION -o out src;
          cd out;
          dotnet nuget push *.nupkg --skip-duplicate --force-english-output -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json;
          dotnet nuget push *.nupkg --skip-duplicate --force-english-output -s https://nuget.pkg.github.com/${{ github.repository.owner }}/index.json;
          
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: out/*
